typography_spectrum: 0.5599995274096727
color:
  brandStrength: 0.9939057517331094
  lightness: 0.10766649735160172
  saturation: 0.4917063903994858
  rhythmicContrast: 0.36653889366425574
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.8648222596384585
name: N'vy Hotel
navigation:
  - name: Hotel
    url: 'http://www.hotelnvygeneva.com/'
    type: external
  - name: Rooms & Suites
    url: 'http://www.hotelnvygeneva.com/chambres-et-suites/'
    type: external
  - name: Bars & Restaurants
    url: 'http://www.hotelnvygeneva.com/bars-et-restaurants/'
    type: external
  - name: Special Offers
    url: 'http://www.hotelnvygeneva.com/offres-speciales/'
    type: external
title: ARTY - COSY - TRENDY
description: T
